# Generated by Django 4.0.2 on 2022-02-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_building_name_alter_room_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(error_messages={'unique': 'this field already exists'}, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='collect_frequency',
            field=models.IntegerField(blank=True, default=300),
        ),
    ]
