# Generated by Django 4.0.2 on 2022-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_building_name_alter_room_collect_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='collect_frequency',
            field=models.IntegerField(default=300),
        ),
    ]
