# Generated by Django 4.0.2 on 2022-02-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datatype_data_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
