# Generated by Django 4.0.2 on 2022-02-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_box_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
