# Generated by Django 4.0.2 on 2022-02-23 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_box_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='last_ping',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='next_ping',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
