# Generated by Django 4.0.2 on 2022-02-23 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_box_last_ping_alter_box_next_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='next_ping',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
