# Generated by Django 4.0.2 on 2022-02-24 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_box_last_ping_alter_box_next_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
