# Generated by Django 4.0.2 on 2022-02-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_room_state_alter_data_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='room',
        ),
        migrations.AddField(
            model_name='data',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.box'),
        ),
    ]
