# Generated by Django 4.0.2 on 2022-02-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_data_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='timeStamp',
            new_name='created_at',
        ),
    ]
