# Generated by Django 4.0.2 on 2022-02-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_timestamp_data_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='box',
            new_name='box_uuid',
        ),
    ]
