# Generated by Django 4.0.2 on 2022-02-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_box_data_box_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='box_uuid',
            new_name='box',
        ),
    ]
