# Generated by Django 4.0.2 on 2022-03-02 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_box_uuid_data_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.room'),
        ),
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
